exclude = [
    '.github',
]
line-length = 120
target-version = "py310"
output-format = "github"

[lint]
extend-select = ["E1", "E2", "E3", "E501", "W"]
ignore = ["F403", "F405"]
preview = true

[lint.per-file-ignores]
"template_code.py" = ["E501"]
"netbox_routing/graphql/filter_mixins.py" = ["F821"]
"netbox_routing/graphql/bgp/types.py" = ["F821"]
"netbox_routing/graphql/community/types.py" = ["F821"]
"netbox_routing/graphql/eigrp/types.py" = ["F821"]
"netbox_routing/graphql/objects/types.py" = ["F821"]
"netbox_routing/graphql/ospf/types.py" = ["F821"]
"netbox_routing/graphql/static/types.py" = ["F821"]
"netbox_routing/graphql/types_mixin.py" = ["F821"]

[format]
quote-style = "single"
